# Generated by Django 4.0.3 on 2022-05-04 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='user_uid',
            field=models.ForeignKey(db_column='user_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='med_salt',
            name='med_uid',
            field=models.ForeignKey(db_column='med_uid', on_delete=django.db.models.deletion.CASCADE, related_name='med_salt_set', to='medicine.medicine'),
        ),
    ]
