# Generated by Django 4.0.3 on 2022-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=30)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_joindate', models.DateTimeField(auto_now=True)),
                ('user_storename', models.CharField(max_length=20)),
                ('user_session', models.CharField(max_length=30)),
            ],
        ),
    ]
