# Generated by Django 4.0.3 on 2022-04-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_user_pw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_pw',
        ),
    ]
