# Generated by Django 4.0.3 on 2022-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_user_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_storename',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
