# Generated by Django 4.0.3 on 2022-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_user_storename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_storename',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
