# Generated by Django 4.0.3 on 2022-05-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_alter_bill_bill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_customer_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_phone',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_profit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_total_sell',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Bill_detail',
        ),
    ]
