# Generated by Django 4.0.3 on 2022-04-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_req',
            name='user_uid',
            field=models.ForeignKey(db_column='user_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
