# Generated by Django 4.0.3 on 2022-04-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_cus_req_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_req',
            name='req_name',
            field=models.CharField(max_length=15),
        ),
    ]
