# Generated by Django 4.0.3 on 2022-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_cus_req_req_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_req',
            name='req_joindate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
