# Generated by Django 4.0.3 on 2022-04-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_uid', models.AutoField(primary_key=True, serialize=False)),
                ('bill_customer_name', models.CharField(max_length=15)),
                ('bill_address', models.CharField(max_length=50)),
                ('bill_phone', models.CharField(max_length=15)),
                ('bill_id', models.CharField(max_length=20)),
                ('bill_total_sell', models.PositiveIntegerField()),
                ('bill_profit', models.PositiveIntegerField()),
                ('bill_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_detail',
            fields=[
                ('detail_uid', models.AutoField(primary_key=True, serialize=False)),
                ('detail_sr_no', models.CharField(max_length=30, null=True)),
                ('detail_med_name', models.CharField(max_length=20)),
                ('detail_qty', models.PositiveIntegerField()),
                ('detail_qty_type', models.CharField(max_length=20)),
                ('detail_unit_price', models.PositiveIntegerField()),
                ('detail_amount', models.PositiveIntegerField()),
                ('bill_uid', models.ForeignKey(db_column='bill_uid', on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
            ],
        ),
    ]
