# Generated by Django 4.0.3 on 2022-04-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('user', '0002_alter_user_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_uid', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=20)),
                ('com_licence_no', models.CharField(max_length=20)),
                ('com_address', models.CharField(max_length=50)),
                ('com_contact_no', models.CharField(max_length=15)),
                ('com_email', models.EmailField(max_length=254)),
                ('com_description', models.TextField()),
                ('com_joindate', models.DateTimeField(auto_now_add=True)),
                ('com_account_no', models.CharField(max_length=20)),
                ('bank_uid', models.ForeignKey(db_column='bank_uid', on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('user_uid', models.ForeignKey(db_column='user_uid', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
