# Generated by Django 4.0.3 on 2022-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_bank_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='com_joindate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
