# Generated by Django 4.0.3 on 2022-04-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('user', '0002_alter_user_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_uid', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=15)),
                ('emp_joindate', models.DateField()),
                ('emp_phone', models.CharField(max_length=15)),
                ('emp_address', models.CharField(max_length=50)),
                ('emp_account_no', models.CharField(max_length=20)),
                ('emp_added_on', models.DateTimeField(auto_now_add=True)),
                ('bank_uid', models.ForeignKey(db_column='bank_uid', on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('user_uid', models.ForeignKey(db_column='user_uid', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('sal_uid', models.AutoField(primary_key=True, serialize=False)),
                ('sal_date', models.DateField()),
                ('sal_amount', models.PositiveIntegerField()),
                ('sal_joindate', models.DateTimeField(auto_now_add=True)),
                ('emp_uid', models.ForeignKey(db_column='emp_uid', on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
