# Generated by Django 4.0.3 on 2022-04-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_bank_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='emp_uid',
            field=models.ForeignKey(db_column='emp_uid', on_delete=django.db.models.deletion.CASCADE, related_name='salary_set', to='employee.employee'),
        ),
    ]
