# Generated by Django 4.0.3 on 2022-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_salary_emp_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='sal_joindate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
